version: "3.8"
services:
  mysql_db:
    container_name: 'mysql_db'
    image: mysql:5.7
    ports:
      - '3307:3306'
    
    
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - mysql_db
